In [182]:
import numpy as np
np.random.seed(0xC0ffee)

class RNN:
    def __init__(self, input_size, output_size, hidden_size, minibatch_size=1):
        self.output_size = output_size
        self.minibatch_size = minibatch_size
        self._W_xh = 0.01 * np.random.uniform(-1.0, 1.0, (hidden_size, input_size))
        self._W_hh = 0.01 * np.random.uniform(-1.0, 1.0, (hidden_size, hidden_size))
        self._b_hh = np.zeros((hidden_size, ))
        self._W_hy = 0.01 * np.random.uniform(-1.0, 1.0, (output_size, hidden_size))
        self._b_hy = np.zeros((output_size,))
        self._h    = np.zeros((hidden_size, minibatch_size))
        
        self.params = [self._W_xh, self._W_hh, self._b_hh, self._W_hy, self._b_hy]
        self.names  = ['Wx', 'Wh', 'bh' 'W', 'b']
        
    def predict(self, x):
        self._x = x
        self._h_raw = np.dot(self._W_hh, self._h) + np.dot(self._W_xh, x)
        for i in range(self.minibatch_size):
            self._h_raw.T[i] += self._b_hh
        self._h = np.tanh( self._h_raw )
        
        y = np.dot(self._W_hy, self._h)
        for i in range(self.minibatch_size):
            y.T[i] += self._b_hy
        
        z = np.zeros((self.output_size, self.minibatch_size))
        for i in range(self.minibatch_size):
            z.T[i] = np.exp( y.T[i] ) / np.sum( np.exp(y.T[i]) ) # softmax
            
        return z
    
    def loss(self, prediction, target):
        return np.sum( - (np.log(prediction) * target) ) # negative log loss (cross-entropy loss)
    
    def delta(self, prediction, target):
        return prediction - target
    
    def backprop(self, delta):
        self._dW_xh = np.zeros_like(self._W_xh)
        self._dW_hh = np.zeros_like(self._W_hh)
        self._db_hh = np.zeros_like(self._b_hh)
        self._dW_hy = np.zeros_like(self._W_hy)
        self._db_hy = np.zeros_like(self._b_hy)
        
        self._dW_xh = np.dot(self._x, delta.T)
        self._dW_hh = np.dot(self._x, delta.T)
        
        
        
            


In [184]:
rnn = RNN(8, 2, 4, 3)
z = rnn.predict( np.array([[1, 2, 1, 2, 1, 2, 1, 2], [1, 2, 1, 2, 1, 2, 1, 2], [1, 2, 1, 2, 1, 2, 1, 2]]).T )
print z
l = rnn.loss(z, np.array([[1, 0], [1, 0], [1, 0]]).T)
print l

[[ 0.50001024  0.50001024  0.50001024]
 [ 0.49998976  0.49998976  0.49998976]]
2.07938011594


In [185]:
d = rnn.delta(z, np.array([[1, 0], [1, 0], [1, 0]]).T)
print d

[[-0.49998976 -0.49998976 -0.49998976]
 [ 0.49998976  0.49998976  0.49998976]]


In [186]:
rnn.backprop( d )

In [ ]:
loss

In [ ]:
np.exp(np.array([1, 2])) / sum(np.exp(np.array([1, 2])))

In [101]:
print np.array([[1, 2], [1, 2], [1, 2]]).shape
print np.array([[1, 2, 3], [1, 2, 3]]).shape

(3, 2)
(2, 3)


In [102]:
np.dot( np.array([[1, 2], [1, 2], [1, 2]]), np.array([[1, 2, 3], [1, 2, 3]]) )

array([[3, 6, 9],
       [3, 6, 9],
       [3, 6, 9]])

In [120]:
np.array([[1, 2, 3], [1, 2, 3]])[0]

array([1, 2, 3])